DROP TABLE RBBS

 CREATE TABLE "C##NOTICEBOARD"."RBBS"
   (	"COMMENT_ID" NUMBER, 
	"NOTICEBOARD_ID" NUMBER, 
	"MANAGEMENT_ID" NUMBER, 
	"NICKNAME" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"CDATE" DATE DEFAULT SYSDATE, 
	"UDATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_NOTICEBOARD" FOREIGN KEY ("NOTICEBOARD_ID")
	  REFERENCES "C##NOTICEBOARD"."NOTICEBOARD" ("NOTICEBOARD_ID") ENABLE, 
	 CONSTRAINT "FK_MANAGEMENT_ID" FOREIGN KEY ("MANAGEMENT_ID")
	  REFERENCES "C##NOTICEBOARD"."MEMBER" ("MANAGEMENT_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;


  ALTER TABLE RBBS DROP CONSTRAINT FK_NOTICEBOARD;

  ALTER TABLE RBBS
  ADD CONSTRAINT fk_noticeboard
  FOREIGN KEY (noticeboard_id)
  REFERENCES NOTICEBOARD(noticeboard_id)
  ON DELETE CASCADE;

  ALTER TABLE RBBS DROP CONSTRAINT FK_MANAGEMENT_ID;

  ALTER TABLE RBBS
  ADD CONSTRAINT FK_MANAGEMENT_ID
  FOREIGN KEY (MANAGEMENT_ID)
  REFERENCES MEMBER(MANAGEMENT_ID)
  ON DELETE CASCADE;
