DROP TABLE RBBS;

CREATE TABLE RBBS (
    COMMENT_ID NUMBER PRIMARY KEY, -- 테이블 관리용 아이디
    NOTICEBOARD_ID NUMBER, -- 게시글 테이블의 PK를 참조
    MANAGEMENT_ID NUMBER, -- 회원 테이블의 PK를 참조
    NICKNAME VARCHAR2(100), -- 댓글 작성자 닉네임
    CONTENT CLOB, -- 본문
    CDATE DATE DEFAULT SYSDATE, -- 작성일
    UDATE DATE DEFAULT SYSDATE, -- 수정일
    PARENT_COMMENT_ID NUMBER,
    CONSTRAINT fk_noticeboard FOREIGN KEY (NOTICEBOARD_ID) REFERENCES NOTICEBOARD(NOTICEBOARD_ID),
    CONSTRAINT fk_MANAGEMENT_ID FOREIGN KEY (MANAGEMENT_ID) REFERENCES MEMBER(MANAGEMENT_ID),
    CONSTRAINT FK_PARENT_COMMENT FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES RBBS(COMMENT_ID)
);

DROP SEQUENCE RBBSTB_COMMENT_ID;
CREATE SEQUENCE RBBSTB_COMMENT_ID;
