DROP TABLE CLASS_CD;

CREATE TABLE CLASS_CD
(
    CODE_ID    VARCHAR2(6) NOT NULL,
    CODE_NM    VARCHAR2(30) NOT NULL,
    UDATE    TIMESTAMP DEFAULT SYSDATE,
    CDATE    TIMESTAMP DEFAULT SYSDATE,
    PCODE_ID    VARCHAR2(6)
);

COMMENT ON COLUMN CLASS_CD.CODE_ID IS '코드아이디';

COMMENT ON COLUMN CLASS_CD.CODE_NM IS '코드명';

COMMENT ON COLUMN CLASS_CD.UDATE IS '수정일';

COMMENT ON COLUMN CLASS_CD.CDATE IS '생성일';

COMMENT ON COLUMN CLASS_CD.PCODE_ID IS '상위코드';

COMMENT ON TABLE CLASS_CD IS '공용코드';

CREATE UNIQUE INDEX CLASS_CD_PK ON CLASS_CD
( CODE_ID );

ALTER TABLE CLASS_CD
 ADD CONSTRAINT CLASS_CD_PK PRIMARY KEY ( CODE_ID )
 USING INDEX CLASS_CD_PK;

ALTER TABLE CLASS_CD
ADD CONSTRAINT CLASS_CDTB_CODE_ID_FK
FOREIGN KEY (PCODE_ID)
REFERENCES CLASS_CD(CODE_ID);

INSERT INTO CLASS_CD(CODE_ID, CODE_NM)
VALUES('B0100','자유');

INSERT INTO CLASS_CD(CODE_ID, CODE_NM,PCODE_ID)
VALUES('B0101','자유','B0100');

INSERT INTO CLASS_CD(CODE_ID, CODE_NM,PCODE_ID)
VALUES('B0102','공략','B0100');

COMMIT;