DROP TABLE MEMBER_PREFER_RECORD;

CREATE TABLE MEMBER_PREFER_RECORD (
    RECORD_ID NUMBER PRIMARY KEY,
    MANAGEMENT_ID NUMBER,
    NOTICEBOARD_ID NUMBER,
    PF_CHECK NUMBER DEFAULT 0,
    CONSTRAINT fk_MEMBER_PREFER_RECORD_NOTICEBOARD_ID_FK FOREIGN KEY (NOTICEBOARD_ID) REFERENCES NOTICEBOARD(NOTICEBOARD_ID),
    CONSTRAINT fk_MEMBER_PREFER_RECORD_MANAGEMENT_ID_FK FOREIGN KEY (MANAGEMENT_ID) REFERENCES MEMBER(MANAGEMENT_ID)
);

ALTER TABLE MEMBER_PREFER_RECORD
DROP COLUMN PF_CHECK;

DROP SEQUENCE MEMBER_PREFER_RECORD_RECORD_ID;
CREATE SEQUENCE MEMBER_PREFER_RECORD_RECORD_ID;
